import pygame

WIN_WIDTH = 700
WIN_HEIGHT = 700
WIN_SIZE = (WIN_WIDTH, WIN_HEIGHT)
FLAGS = pygame.FULLSCREEN | pygame.SCALED
BLACK =(0, 0, 0)
GREEN = (0, 255, 0)

PLAYER_HEIGHT = 200
PLAYER_WIDTH = 20

PLAYER_SPEED = 5

BALL_WIDTH = 35
BALL_HEIGHT = 35
BALL_SPEED = 5